import type { Metadata } from "next";
import { site } from "./site";
import type { Locale } from "./i18n";

type Args = { lang: Locale; path?: string; title: string; description: string };

// Share cards are generated by `npm run build:og` into public/og.
const TOP = ["about", "services", "plants", "projects", "gallery", "contact"];
function cardFor(lang: Locale, path: string) {
  const [a, b] = path.split("/").filter(Boolean);
  const key = !a ? "default" : b ? `${a === "services" ? "service" : "project"}-${b}` : TOP.includes(a) ? a : "default";
  return `/og/${lang}-${key}.jpg`;
}

export function pageMeta({ lang, path = "", title, description }: Args): Metadata {
  const url = `${site.url}/${lang}${path}`;
  const og = cardFor(lang, path);
  return {
    title,
    description,
    alternates: {
      canonical: url,
      languages: { en: `${site.url}/en${path}`, ar: `${site.url}/ar${path}`, "x-default": `${site.url}/en${path}` },
    },
    openGraph: {
      title, description, url, siteName: site.name, type: "website",
      locale: lang === "ar" ? "ar_AE" : "en_AE",
      images: [{ url: og, width: 1200, height: 630, alt: title }],
    },
    twitter: { card: "summary_large_image", title, description, images: [og] },
  };
}
